### ISSUE TITLE
SwlData | Unit test

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/hmi_widgets#20]
assert length of loaded lists, all must be same.

**Comment by Minyewoo** [comment]
Related PR: https://github.com/a-givertzman/hmi_widgets/pull/26
File: https://github.com/a-givertzman/hmi_widgets/pull/26/files#diff-333ebcb9c0704123d0b5b242b0ca100c5d0e37a2bc7c63bc1b55eb804c270668
