### ISSUE TITLE
Move widgets to hmi_widgets

### ISSUE THREAD

**Issue by Minyewoo** [a-givertzman/hmi_widgets#21]
Move the following dirs from crane_monitoring_app (branch Add-hmi_widgets-package):
- [x] `lib/presentation/core/widgets/edit_field/*` -> `lib/src/edit_field/*`
- [x] `lib/presentation/core/widgets/drive/*` -> `lib/src/process/electrical/drive/*`

**Comment by a-givertzman** [comment]
coverage issue will be fixes by this [issue](https://github.com/a-givertzman/hmi_core/issues/37#issue-1569400513)
