### ISSUE TITLE
Import initial code

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/hmi_widgets#3]
Import initial code from main project
- [ ] heme
- [ ] dialogs
- [ ] buttons
- [ ] popups
- [ ] indicators
   - [ ] status_indicators
      - [x] SpsIconIndicator
      - [x] DpsIconIndicator
      - [x] BoolColorIndicator
      - [x] InvalidStatusIndicator
   - [ ] value_indicators
- [x] charts
   - [x] CraneLoadChart
   - [x] CranePositionChart

**Comment by Minyewoo** [comment]
> Import initial code from main project
> 
>     * [ ]  heme
> 
>     * [ ]  dialogs
> 
>     * [ ]  buttons
> 
>     * [ ]  popups
> 
>     * [ ]  indicators
>       
>       * [ ]  status_indicators
>         
>         * [x]  SpsIconIndicator
>         * [x]  DpsIconIndicator
>         * [x]  BoolColorIndicator
>         * [x]  InvalidStatusIndicator
>       * [ ]  value_indicators
> 
>     * [x]  charts
>       
>       * [x]  CraneLoadChart
>       * [x]  CranePositionChart
